extends:
  - 'eslint:recommended'
env:
  browser: true
  es6: true
  node: true
parserOptions:
  sourceType: module
rules:
  block-spacing:
    - error
    - never
  keyword-spacing:
    - error
    - after: true
      before: true
  quotes:
    - error
    - single
  semi: error
